# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Hosting

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  deploy-to-live-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to Website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          exclude: ".git*"
